In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
clean_df = pd.read_csv(
    "../data/cleaned/online_retail_cleaned.csv",
    parse_dates=["InvoiceDate"]
)

clean_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [4]:
clean_df["InvoiceDate"].max()

snapshot_date = clean_df["InvoiceDate"].max() + pd.Timedelta(days=1)

print(snapshot_date)

2023-12-10 12:50:00

In [5]:
rfm = clean_df.groupby("CustomerID").agg({

    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,

    "InvoiceNo": "nunique",

    "Revenue": "sum"

})

In [7]:
rfm.columns = [

    "Recency",

    "Frequency",

    "Monetary"

]

rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40

In [8]:
rfm = rfm.reset_index()

rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

In [9]:
rfm.describe()

         CustomerID      Recency    Frequency       Monetary
count   4338.000000  4338.000000  4338.000000    4338.000000
mean   15300.408022    92.536422     4.272015    2048.688081
std     1721.808492   100.014169     7.697998    8985.230220
min    12346.000000     1.000000     1.000000       3.750000
25%    13813.250000    18.000000     1.000000     306.482500
50%    15299.500000    51.000000     2.000000     668.570000
75%    16778.750000   142.000000     5.000000    1660.597500
max    18287.000000   374.000000   209.000000  280206.020000

In [10]:
rfm.to_csv(

    "../data/processed/rfm_dataset.csv",

    index=False

)

print("RFM Dataset Saved Successfully!")

RFM Dataset Saved Successfully!

In [11]:
print(rfm.shape)

print(rfm.info())

print(rfm.isnull().sum())

(4338, 4)
<class 'pandas.DataFrame'>
RangeIndex: 4338 entries, 0 to 4337
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  4338 non-null   float64
 1   Recency     4338 non-null   int64
 2   Frequency   4338 non-null   int64
 3   Monetary    4338 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 135.7 KB
None
CustomerID    0
Recency       0
Frequency     0
Monetary      0
dtype: int64

| Feature   | Formula                         | Business Meaning     |
| --------- | ------------------------------- | -------------------- |
| Recency   | Snapshot Date − Latest Purchase | Customer freshness   |
| Frequency | Number of Unique Invoices       | Purchase consistency |
| Monetary  | Sum of Revenue                  | Customer value       |